spring.application.name=projetEncheres


spring.datasource.url=jdbc:sqlserver://localhost;databasename=projet_enchere;integratedSecurity=false;encrypt=false;trustServerCertificate=false
spring.datasource.username=sa
spring.datasource.password=Pa$$w0rd
